### ISSUE TITLE
Is the repository no more part of hacktoberfest 2022 ?

### ISSUE THREAD

**Issue by sayskar500** [HemangJoshi/hacktoberfest-2022#71]
I am asking this question because in the recent closed PR requests I cannot see the **hacktoberfest accepted** tag.

![image](https://user-images.githubusercontent.com/55600400/194879447-877cc74d-4a58-4d22-a608-99ad2b366cdf.png)

**Comment by HemangJoshi** [comment]
this repo is still a part of hacktober fest.
but due to some personal issues, the reviewing process of the pull request was slowed down.
Also if your pr is merged in this repo without any spam tagging then it is automatically recognized as a valid PR and counted in the hacktoberfest the tag is provided to differentiate between regular PRs and those accepted during hacktoberfest.

**Comment by HemangJoshi** [comment]
if you still have any doubts pls continue else the issue will be closed after 24 hrs of inactivity.

**Comment by sayskar500** [comment]
noted!

again thanks for replying back so fast.
